/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quizgame.UI;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.plaf.metal.MetalIconFactory;
import quizgame.Domanda;
import quizgame.Giocatore;
import quizgame.QuizGame;

/**
 *
 * @author Andrea.casamatta
 */
public class DomandaMultipla extends javax.swing.JPanel {

    /**
     * Creates new form Domanda
     */
    private QuizGame quizGame;
    private Impostazioni impo1;

    public DomandaMultipla(QuizGame quizGame, Impostazioni impo1) {
        this.quizGame = quizGame;
        this.impo1 = impo1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nomeGiocatore = new javax.swing.JLabel();
        numDomanda = new javax.swing.JLabel();
        scelta1 = new javax.swing.JRadioButton();
        scelta2 = new javax.swing.JRadioButton();
        risponde = new javax.swing.JLabel();
        scelta3 = new javax.swing.JRadioButton();
        scelta4 = new javax.swing.JRadioButton();
        contentDomanda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(793, 443));

        nomeGiocatore.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        nomeGiocatore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeGiocatore.setText("nomeGiocatore");

        numDomanda.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        numDomanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numDomanda.setText("num domanda");

        buttonGroup1.add(scelta1);
        scelta1.setText("1");
        scelta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scelta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(scelta2);
        scelta2.setSelected(true);
        scelta2.setText("2");
        scelta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scelta2ActionPerformed(evt);
            }
        });

        risponde.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        risponde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        risponde.setText("risponde");

        buttonGroup1.add(scelta3);
        scelta3.setText("3");
        scelta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scelta3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(scelta4);
        scelta4.setText("4");
        scelta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scelta4ActionPerformed(evt);
            }
        });

        contentDomanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contentDomanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contentDomanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scelta3)
                    .addComponent(scelta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scelta4)
                    .addComponent(scelta2))
                .addGap(304, 304, 304))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeGiocatore, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(risponde, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224)
                .addComponent(numDomanda)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(contentDomanda, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeGiocatore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(risponde, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numDomanda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(contentDomanda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scelta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scelta2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scelta3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scelta4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents
    private String rispostaCorretta;
    private String risposta;
    Giocatore giocatore1;
    private void scelta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scelta2ActionPerformed
        // TODO add your handling code here:
        risposta = scelta2.getText();
    }//GEN-LAST:event_scelta2ActionPerformed

    private void scelta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scelta1ActionPerformed
        // TODO add your handling code here:
        risposta = scelta1.getText();
    }//GEN-LAST:event_scelta1ActionPerformed

    private void scelta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scelta3ActionPerformed
        // TODO add your handling code here:
        risposta = scelta3.getText();
    }//GEN-LAST:event_scelta3ActionPerformed

    private void scelta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scelta4ActionPerformed
        // TODO add your handling code here:
        risposta = scelta4.getText();
    }//GEN-LAST:event_scelta4ActionPerformed

    public void scegliGiocatore(int numGiocatore) {
        List<Giocatore> nomiGiocatori = quizGame.getGiocatori();
        Giocatore giocatoreScelto = nomiGiocatori.get(numGiocatore);
        nomeGiocatore.setText(giocatoreScelto.getNomeUtente());
        giocatore1 = giocatoreScelto;
    }

    public void verificaRisposta() {
        System.out.println("Verifico Multipla");
        if (risposta.equals(rispostaCorretta)) {
            giocatore1.aggiornaPunteggio();
            
        }
        System.out.println(giocatore1.getPunteggio());

    }

    public void scegliDomanda(int numeroDomanda) {
        String cat = impo1.getCategoria();
        String diff = impo1.getDifficolta();
        contentDomanda.setText("");
        numDomanda.setText(Integer.toString(numeroDomanda));
        quizGame.QuizGame();
        List<Domanda> domanda = quizGame.getDomande();
        List<Domanda> domandeUtili = new ArrayList<>();
        int contaDomande = 0;
        for (int i = 0; i < domanda.size(); i++) {
            if ((domanda.get(i).getTipoRisposta().equals("Multipla")) && (domanda.get(i).getCategoria().equals(cat)) && (domanda.get(i).getDifficolta().equals(diff))) {
                domandeUtili.add(domanda.get(i));
                contaDomande++;
            }
        }

        if (contaDomande > 0) {
            Random random = new Random();
            int indiceCasuale = random.nextInt(contaDomande);
            Domanda domandaCasuale = domandeUtili.get(indiceCasuale);
            contentDomanda.setText(domandaCasuale.getTesto());
            List<String> scelte = domandaCasuale.getRisposte();
            scelta1.setText(scelte.get(0));
            scelta2.setText(scelte.get(1));
            scelta3.setText(scelte.get(2));
            scelta4.setText(scelte.get(3));
            risposta = scelta2.getText();
            rispostaCorretta = domandaCasuale.getRispostaCorretta();

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel contentDomanda;
    private javax.swing.JLabel nomeGiocatore;
    private javax.swing.JLabel numDomanda;
    private javax.swing.JLabel risponde;
    private javax.swing.JRadioButton scelta1;
    private javax.swing.JRadioButton scelta2;
    private javax.swing.JRadioButton scelta3;
    private javax.swing.JRadioButton scelta4;
    // End of variables declaration//GEN-END:variables
}
